package Cell;


/**
* Cell/TubeCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, May 16, 2018 1:27:36 PM MSK
*/


/* ????????? ????????? ?????? ?????? */
public interface TubeCallback extends TubeCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TubeCallback
