module Cell {
  /* ????????? ????????? ?????? ?????? */
  interface TubeCallback {
    /* ??????? ????????? message ?? ?????? fromNum */
    long sendSMS (in string fromNum, in string message);
    /* ??????? ???? ????? */
    string getNum();
    };

  /* ????????? ??????? ??????? */
  interface Station {
    /* ???????????????? ?????? ? ??????? phoneNum, */
    /* ??? ????????? ?????? ?????? ???????????? ?????? TubeCallback */
    long register (in TubeCallback objRef, in string phoneNum);
    /* ????????? ????????? message ?? ?????? fromNum ? ?????? toNum */
    long sendSMS (in string fromNum, in string toNum, in string message);
    };

  }; 
